//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.Database.PostgreSql.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.Database.PostgreSql.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DbManager type=&quot;Utility.Database.PostgreSql.PgDbManager, Utility.Database.PostgreSql&quot;&gt;
        ///  &lt;DbDescription type=&quot;Utility.Database.PostgreSql.PgDbDescription, Utility.Database.PostgreSql&quot;&gt;
        ///    &lt;Connection&gt;
        ///      &lt;ConnectionStringName&gt;Test1&lt;/ConnectionStringName&gt;
        ///    &lt;/Connection&gt;
        ///    &lt;Schema type=&quot;Resource&quot;&gt;Utility.Database.PostgreSql.Test.Resources.TestSchema.sql&lt;/Schema&gt;
        ///    &lt;Seed type=&quot;Resource&quot;&gt;Utility.Database.PostgreSql.Test.Resources.TestSeed.sql&lt;/Seed&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDescription {
            get {
                return ResourceManager.GetString("TestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DbManager type=&quot;Utility.Database.PostgreSql.PgDbManager, Utility.Database.PostgreSql&quot;&gt;
        ///  &lt;DbDescription type=&quot;Utility.Database.PostgreSql.PgDbDescription, Utility.Database.PostgreSql&quot;&gt;
        ///    &lt;Schema type=&quot;Resource&quot;&gt;Utility.Database.PostgreSql.Test.Resources.TestSchema.sql&lt;/Schema&gt;
        ///    &lt;Seed type=&quot;Resource&quot;&gt;Utility.Database.PostgreSql.Test.Resources.TestSeed.sql&lt;/Seed&gt;
        ///    &lt;Seed type=&quot;Literal&quot;&gt;INSERT INTO test_schema.test_table (name) VALUES(&apos;name3&apos;);&lt;/Seed&gt;
        ///  &lt;/D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDescriptionNoConnectionName {
            get {
                return ResourceManager.GetString("TestDescriptionNoConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DbManager type=&quot;Utility.Database.PostgreSql.PgDbManager, Utility.Database.PostgreSql&quot;&gt;
        ///  &lt;DbDescription type=&quot;Utility.Database.PostgreSql.PgDbDescription, Utility.Database.PostgreSql&quot;&gt;
        ///    &lt;Connection&gt;
        ///      &lt;ConnectionStringName&gt;Test1&lt;/ConnectionStringName&gt;
        ///    &lt;/Connection&gt;
        ///    &lt;TemplateName&gt;template_postgis&lt;/TemplateName&gt;
        ///    &lt;Schema type=&quot;Resource&quot;&gt;Utility.Database.PostgreSql.Test.Resources.TestSchema.sql&lt;/Schema&gt;
        ///    &lt;Seed type=&quot;Resource&quot;&gt;Utility.Databas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDescriptionWithTemplate {
            get {
                return ResourceManager.GetString("TestDescriptionWithTemplate", resourceCulture);
            }
        }
    }
}
